name: story_app
description: "Dicoding Story App - Share your learning moments."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  json_annotation: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.11.0

flutter:
  uses-material-design: true
